#! /bin/sh
### BEGIN INIT INFO
# Provides:          post-boot
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1
# Short-Description: Run post-boot configuration
# Description: The first purpose of this script is to set the sysfs
#              settings required for Eagle
### END INIT INFO

PATH=/bin:/usr/bin

case "$1" in
  start|restart|force-reload|reload)
    target=`uname -r | cut -d'-' -f2`
    case "$target" in
        "sdflight")
            echo 4 > /sys/module/lpm_levels/enable_low_power/l2
            echo 1 > /sys/module/msm_pm/modes/cpu0/power_collapse/suspend_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu1/power_collapse/suspend_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu2/power_collapse/suspend_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu3/power_collapse/suspend_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu0/power_collapse/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu1/power_collapse/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu2/power_collapse/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu3/power_collapse/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu0/standalone_power_collapse/suspend_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu1/standalone_power_collapse/suspend_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu2/standalone_power_collapse/suspend_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu3/standalone_power_collapse/suspend_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu0/standalone_power_collapse/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu1/standalone_power_collapse/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu2/standalone_power_collapse/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu3/standalone_power_collapse/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu0/retention/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu1/retention/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu2/retention/idle_enabled
            echo 1 > /sys/module/msm_pm/modes/cpu3/retention/idle_enabled
            echo 0 > /sys/module/msm_thermal/core_control/enabled
            echo 1 > /sys/devices/system/cpu/cpu1/online || true
            echo 1 > /sys/devices/system/cpu/cpu2/online || true
            echo 1 > /sys/devices/system/cpu/cpu3/online || true
            if [ -f /sys/devices/soc0/soc_id ]; then
                soc_id=`cat /sys/devices/soc0/soc_id`
            else
                soc_id=`cat /sys/devices/system/soc/soc0/id`
            fi
            case "$soc_id" in
                "208" | "211" | "214" | "217" | "209" | "212" | "215" | "218" | "194" | "210" | "213" | "216")
                    for devfreq_gov in /sys/class/devfreq/qcom,cpubw*/governor
                    do
                        echo "cpubw_hwmon" > $devfreq_gov
                    done
                    echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                    echo "interactive" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
                    echo "interactive" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
                    echo "interactive" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
                    echo "20000 1400000:40000 1700000:20000" > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
                    echo 90 > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
                    echo 1190400 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
                    echo 1 > /sys/devices/system/cpu/cpufreq/interactive/io_is_busy
                    echo "85 1500000:90 1800000:70" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
                    echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
                    echo 20 > /sys/module/cpu_boost/parameters/boost_ms
                    echo 1728000 > /sys/module/cpu_boost/parameters/sync_threshold
                    echo 100000 > /sys/devices/system/cpu/cpufreq/interactive/sampling_down_factor
                    echo 1497600 > /sys/module/cpu_boost/parameters/input_boost_freq
                    echo 40 > /sys/module/cpu_boost/parameters/input_boost_ms
                ;;
                *)
                    echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                    echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
                    echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
                    echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
                    echo 50000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
                    echo 90 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
                    echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
                    echo 2 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
                    echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
                    echo 70 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core
                    echo 3 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential_multi_core
                    echo 960000 > /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq
                    echo 960000 > /sys/devices/system/cpu/cpufreq/ondemand/sync_freq
                    echo 1190400 > /sys/devices/system/cpu/cpufreq/ondemand/input_boost
                    echo 80 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load
                ;;
            esac
            echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
            echo 300000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
            echo 300000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
            echo 300000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
            echo 1 > /sys/module/msm_thermal/core_control/enabled
            echo 512 > /sys/block/mmcblk0/bdi/read_ahead_kb
        ;;
    esac
  stop)
	# nothing to do
    :
    ;;
  status)
    exit 4
    ;;
  *)
    echo "Usage: /etc/init.d/start-stop {start|stop|restart|force-reload|reload}"
    exit 2
    ;;
esac

exit 0
