#!/bin/sh
# Copyright (c) 2015, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

[ -d /dev ] || mkdir -m 0755 /dev
[ -d /root ] || mkdir -m 0700 /root
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp
mkdir -p /var/lock
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t proc -o nodev,noexec,nosuid proc /proc
# Some things don't work properly without /etc/mtab.
ln -sf /proc/mounts /etc/mtab

echo "Loading, please wait..."

# Turn on the green LED
BLUE_LED_BLINK=/sys/class/leds/blue/blink
GREEN_LED_BLINK=/sys/class/leds/green/blink
RED_LED_BLINK=/sys/class/leds/red/blink
echo 0 > ${BLUE_LED_BLINK}
echo 1 > ${GREEN_LED_BLINK}

# Note that this only becomes /dev on the real filesystem if udev's scripts
# are used; which they will be, but it's worth pointing out
if ! mount -t devtmpfs -o mode=0755 udev /dev; then
	echo "W: devtmpfs not available, falling back to tmpfs for /dev"
	mount -t tmpfs -o mode=0755 udev /dev
	[ -e /dev/console ] || mknod -m 0600 /dev/console c 5 1
	[ -e /dev/null ] || mknod /dev/null c 1 3
fi
mkdir /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
mount -t tmpfs -o "noexec,nosuid,size=10%,mode=0755" tmpfs /run

. /scripts/functions

# Need some time to create the sysfs nodes
sleep 5

/bin/init_adbd

# Create partitions by-name links
log_begin_msg "Mounting partitions\n"
for f in `ls /sys/class/block/mmcblk0p*/uevent`; do
    name=`awk -F'=' '/PARTNAME/ {print $2}' $f`
    sys_path=${f%/*}
    device=${sys_path##*/}
    platform=/dev/block/platform/msm_sdcc.1/by-name
    mkdir -p $platform
    ln -sf /dev/${device} ${platform}/${name}
done

# Mount system to copy build.prop
[ -d /system ] || mkdir /system
mount -t ext4 /dev/block/platform/msm_sdcc.1/by-name/system /system

# Copy build.prop from system to /tmp
if [ -f "/system/build.prop" ]; then
    cp /system/build.prop /tmp/build.prop
else
    # Copy from ramdisk if the system got corrupted (only has board name)
    cp /build.prop /tmp/build.prop
fi
umount /system
log_end_msg

# Run recovery
log_begin_msg "Running recovery\n"
recovery
ret=$?
log_end_msg

# Print log
echo "Recovery log:"
echo "$(cat /tmp/recovery.log)"
echo ""

if [ $ret -eq 0 ]; then
    reboot
else
    # Turn on the red LED
    echo 0 > ${GREEN_LED_BLINK}
    echo 1 > ${RED_LED_BLINK}
    /bin/sh
fi
