#!/bin/sh
# quit if we're called for the loopback
if [ "$IFACE" = lo ]; then
        exit 0
fi

case "$MODE" in 
        start)
                case "$PHASE" in
                        pre-up)
                                ifconfig eth0 hw ether @REPLACE_WITH_REAL_MAC_ADDR@
                                ;;
                esac
                ;;
esac

exit 0

