# Simple Makefile to compile hello.c. 
# Needed because hello.c can't actually be cross-compiled from the command
# line. The Makefile takes advantage of the environment variables set up by the
# environment-setup-<target> script to correctly cross-compile.
hello: hello.c
