#!/bin/sh
### BEGIN INIT INFO
# Provides:        resize_root_partition  
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 
# Default-Stop:      0
# Short-Description: Resize the filesystem
# Description:       This script resizes the root filesystem to use the entire partition.
### END INIT INFO
###############################################################################
## Author: Gene Marsh (gmarsh@codeaurora.org)
## 
###############################################################################
##
## Resize the root file ssytem.
##

if [ ! -e /usr/local/qr-linux/.resized_root_partition ]; then
   LK_ROOT_DEV=`cat /proc/cmdline | sed "s|.*root=\([A-Za-z0-9/]\+\).*|\1|"`
   /sbin/resize2fs ${LK_ROOT_DEV}
   touch /usr/local/qr-linux/.resized_root_partition
fi
