#!/bin/bash

# Usage: debiff <source> <target> <patch>
# Format:
# - Header (8 bytes): DEBIFF10
# - Size of control.tar.p
# - Contents of control.tar.p
# - Size of data.tar.p
# - Contents of data.tar.p

source=$1
target=$2
patch=$3

# Create random temporary folder
tmp=`mktemp -d`

# Obtain control and data tar from source and target
dpkg-deb --control-tarfile $source > $tmp/control.src.tar
dpkg-deb --fsys-tarfile $source > $tmp/data.src.tar
dpkg-deb --control-tarfile $target > $tmp/control.dst.tar
dpkg-deb --fsys-tarfile $target > $tmp/data.dst.tar

mkdir -p $tmp/patch
bsdiff $tmp/control.src.tar $tmp/control.dst.tar $tmp/patch/control.tar.p
bsdiff $tmp/data.src.tar $tmp/data.dst.tar $tmp/patch/data.tar.p

echo -e -n "DEBIFF10" > $patch

size=`stat --printf="%s" $tmp/patch/control.tar.p`
printf "0: %.16x" $size | xxd -r -g0 >> $patch
cat $tmp/patch/control.tar.p >> $patch

size=`stat --printf="%s" $tmp/patch/data.tar.p`
printf "0: %.16x" $size | xxd -r -g0 >> $patch
cat $tmp/patch/data.tar.p >> $patch

# Delete the temporary folder
rm -rf $tmp
