#!/bin/sh		
# quit if we're called for the loopback		
if [ "$IFACE" != eth0 ]
then		
    exit 0		
fi

case "$MODE" in 		
    start)		
        case "$PHASE" in		
            pre-up)
                # This script is named so that it gets called after
		# if-pre-up.d/eth0. Running that script would've put the
		# MAC address after "ether" in the line below
                ifconfig eth0 hw ether 
                ;;
        esac
        ;;
esac
exit 0
