#!/bin/sh		
# quit if we're called for the loopback		
if [ "$IFACE" != eth0 ]
then		
    exit 0		
fi

case "$MODE" in 		
    start)		
        case "$PHASE" in		
            pre-up)
                # Here we obtain the MAC address from usual IFC6410 locations
		# The script below will write that MAC addr in another file
		# in this same dir, named to run after this script, that will
		# actually set the MAC address for that HW
                /usr/local/qr-linux/qrl-config-macaddr.sh -i eth -m auto -r
                ;;
        esac
        ;;
esac
exit 0
